## Prediction of linear site terms using microtremor horizontal-to-vertical spectral ratios (mHVSR)

The notebook is intended to illustrate the prediction of site terms using mHVSR based on Artificial Neural Network (ANN) Ensemble models.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Average
import os

In [2]:
#Load mHVSR data

hvsr_df = pd.read_csv('HVSR_data.csv')
display(hvsr_df.head())

,Network,Station,Instrument_code,HVSR@f=0.100Hz,HVSR@f=0.121Hz,HVSR@f=0.145Hz,HVSR@f=0.175Hz,HVSR@f=0.210Hz,HVSR@f=0.253Hz,HVSR@f=0.305Hz,...,HVSR@f=8.588Hz,HVSR@f=10.337Hz,HVSR@f=12.444Hz,HVSR@f=14.979Hz,HVSR@f=18.031Hz,HVSR@f=21.705Hz,HVSR@f=26.127Hz,HVSR@f=31.451Hz,HVSR@f=37.859Hz,HVSR@f=45.572Hz
0,2F,TB007,HH,0.970469,1.148358,0.709258,0.718100,0.708313,0.921902,0.737007,...,1.397555,1.382754,0.696909,0.544273,0.926739,1.050005,1.079146,1.017911,0.976224,0.926692
1,2F,TB009,HH,0.905063,0.763186,0.836994,0.882180,0.887081,0.873135,0.942550,...,1.404083,1.399744,1.319416,0.953986,0.933590,1.122871,1.375086,1.175145,1.034019,0.950343
2,2F,TB010,HH,0.702001,0.647027,0.868706,0.715756,0.765654,0.582792,0.867919,...,1.384676,1.261087,1.229468,0.881491,0.834996,0.820495,0.439261,0.430127,0.570531,0.910400
3,2F,TB011,HH,2.141755,1.416672,1.275430,1.623695,1.584829,1.650877,2.021388,...,1.006449,0.978036,0.951096,0.691554,0.708172,0.714486,0.993506,0.968050,0.957030,0.926971
4,2F,TB012,HH,2.218786,1.871183,1.557066,1.313637,1.325204,1.638061,1.484710,...,1.029490,0.940138,0.909199,0.927993,0.966099,1.086986,1.291067,1.398478,0.938838,0.933680

In [3]:
model_dir = r'ANN1/'
site_term_freqs = np.sort([float(i) for i in os.listdir(model_dir)])

In [4]:
#Predicting site terms 

input_vals = np.log(hvsr_df.iloc[:,3:])
predictions_df = hvsr_df.iloc[:,:3]

for f in site_term_freqs:
    models = [tf.keras.models.load_model(fr'ANN1/{f}/model_{k}.keras') for k in range(1,8)]  
    predictions = np.array([m.predict(input_vals,verbose = 0).ravel() for m in models])
    ensemble_predictions = np.mean(predictions,axis=0)
    predictions_df[f'SiteTerm@{f}Hz']  = ensemble_predictions

In [5]:
predictions_df

,Network,Station,Instrument_code,SiteTerm@0.1Hz,SiteTerm@0.126Hz,SiteTerm@0.158Hz,SiteTerm@0.2Hz,SiteTerm@0.251Hz,SiteTerm@0.316Hz,SiteTerm@0.398Hz,...,SiteTerm@2.512Hz,SiteTerm@3.162Hz,SiteTerm@3.981Hz,SiteTerm@5.012Hz,SiteTerm@6.31Hz,SiteTerm@7.943Hz,SiteTerm@10.0Hz,SiteTerm@12.589Hz,SiteTerm@15.849Hz,SiteTerm@19.953Hz
0,2F,TB007,HH,0.115761,0.137685,0.025501,-0.016310,-0.173895,-0.312773,-0.225232,...,-0.488316,-0.159258,0.442653,0.948582,1.187682,1.427500,1.220119,1.410105,1.430321,1.453231
1,2F,TB009,HH,0.163205,0.037927,0.283164,0.131849,0.244094,0.162812,0.160063,...,0.875482,0.683276,0.691122,0.581722,0.622795,0.517864,0.415165,0.667671,0.254887,0.535747
2,2F,TB010,HH,-0.017130,0.029438,0.151069,0.163511,0.069176,0.112539,0.007079,...,-0.131721,0.147845,-0.338163,-0.320387,-0.104068,-0.075120,0.178110,0.112485,0.730236,0.667224
3,2F,TB011,HH,0.413321,0.372450,0.595032,0.782712,0.859992,1.194040,0.985579,...,0.544170,0.444633,0.568074,0.425895,0.528689,0.164216,0.316550,0.129350,-0.055681,-0.394012
4,2F,TB012,HH,0.536084,0.621797,0.725136,0.860182,1.016834,1.142159,1.154486,...,0.409157,0.186449,0.177518,0.021751,-0.291982,-0.261148,-0.383532,-0.698086,-0.904376,-0.849961
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1100,YX,UNM4,HH,0.361387,0.393652,0.357098,0.543085,0.469120,0.495136,0.571355,...,-0.060164,0.026135,0.065326,0.204951,0.208291,0.158065,0.205761,0.014787,-0.128157,-0.614464
1101,YX,UNM5,HH,0.507185,0.370583,0.616753,0.526746,0.602925,0.380465,0.312953,...,-0.341932,-0.011819,-0.092702,0.197154,0.155285,0.478463,0.588257,0.373096,-0.034512,-0.358091
1102,YX,UNM6,HH,0.322230,0.254065,0.500263,0.581686,0.575853,0.726246,0.271881,...,-0.130448,-0.156181,-0.021449,0.186670,0.269482,0.527967,0.813698,0.360551,-0.210857,-0.450007
1103,YX,UNM7,HH,0.357858,0.394716,0.366257,0.547897,0.615407,0.414064,0.633911,...,0.560740,0.118997,0.308930,0.114518,-0.050001,-0.279911,-0.488711,-0.472874,-0.740875,-0.487095
1104,ZY,SV02,HH,0.306225,0.210493,0.196092,0.009183,0.112949,0.074104,0.635532,...,0.314720,0.154038,-0.062702,-0.142102,0.010369,-0.047906,-0.165191,-0.318721,-0.388310,-0.812410